//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmp307
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public int HardwareID { get; set; }
        public int EmployeeResponsible { get; set; }
        public string AssetName { get; set; }
        public string comment { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
