//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmp307
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.assets = new HashSet<asset>();
        }

        public int EmployeeID { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string Email { get; set; }
        public Nullable<int> DepartmentID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset> assets { get; set; }
        public virtual Department Department { get; set; }

        public static bool CheckIfExists(int ID)
        {

            using (mssql2100902Entities check = new mssql2100902Entities())
            {
                var find = check.Employees.Where(e => e.EmployeeID == ID).SingleOrDefault<Employee>();
                if (find != null)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }



        }
    }
}
