//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmp307
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Software
    {
        public int SoftwareID { get; set; }
        public string SoftwareName { get; set; }

        public static bool CheckID(int ID)
        {
            using (mssql2100902Entities check = new mssql2100902Entities())
            {

                var find = check.Softwares.Where(e => e.SoftwareID == ID).SingleOrDefault<Software>();
                if (find == null)
                {
                    return false;
                }
                else
                {
                    return true;
                }
            }
        }

        public static void AddSoftware(Software software)
        {
            using (mssql2100902Entities add = new mssql2100902Entities())
            {
                add.Softwares.Add(software);
                add.SaveChanges();
            }
        }

        public static void EditSoftware(Software software)
        {
            using (mssql2100902Entities edit = new mssql2100902Entities())
            {
                var find = edit.Softwares.Where(e => e.SoftwareID == software.SoftwareID).SingleOrDefault<Software>();
                find.SoftwareName = software.SoftwareName;
                edit.SaveChanges();
            }
        }

        public static void DelSoftware(int ID)
        {
            using (mssql2100902Entities del = new mssql2100902Entities())
            {
                var find = del.Softwares.Where(e => e.SoftwareID == ID).SingleOrDefault<Software>();
                del.Softwares.Remove(find);
                del.SaveChanges();
            }
        }
    }
}
