//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmp307
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SoftwareLink
    {
        public int LinkID { get; set; }
        public Nullable<int> HardwareID { get; set; }
        public Nullable<int> SoftwareID { get; set; }
        public Nullable<System.DateTime> DateOfLink { get; set; }




        public static void AddLink(SoftwareLink Link)
        {
            using (mssql2100902Entities New = new mssql2100902Entities())
            {
                New.SoftwareLinks.Add(Link);
                New.SaveChanges();
            }
        }

        public static void DelLink(int ID)
        {
            using (mssql2100902Entities Del = new mssql2100902Entities())
            {
                var find = Del.SoftwareLinks.Where(e => e.LinkID == ID).SingleOrDefault<SoftwareLink>();
                Del.SoftwareLinks.Remove(find);
                Del.SaveChanges();
            }
        }

        public static bool CheckIDNum(int ID)
        {
            using (mssql2100902Entities check = new mssql2100902Entities())
            {
                var find = check.SoftwareLinks.Where(e => e.LinkID == ID).SingleOrDefault<SoftwareLink>();
                if (find == null)
                {
                    return true;
                }
                else
                {
                    return false;
                }



            }
        }

    }
}
